### ISSUE TITLE
Xcode error: Cannot find type 'JSONEncoder' in scope in Xcode Version 12.4

### ISSUE THREAD

**Issue by xta** [guykogus/CodableGeoJSON#3]
I added https://github.com/guykogus/CodableGeoJSON (v2.0.0) via Xcode's built in Swift Package Manager. Xcode is giving me 4 errors. See attached screenshot. Thanks

<img width="1193" alt="xcode_errors" src="https://user-images.githubusercontent.com/465358/107872817-e5ba3180-6e61-11eb-9935-c0a9acf913b5.png">

**Comment by guykogus** [comment]
Can you please try and update the package and see if it still happens? The dependency on `CodableJSON` seems to have caused this.
